from typing import Protocol
from uuid import UUID

from domain.conversation.entities import Command, Conversation, GroundedAnswer
from domain.events import DomainEvent
from domain.voice.entities import AudioResponse, Translation


class ConversationRepositoryPort(Protocol):
    async def save_conversation(self, conversation: Conversation) -> None: ...

    async def get_conversation(self, conversation_id: UUID) -> Conversation | None: ...

    async def save_command(self, command: Command) -> None: ...

    async def get_command(self, command_id: UUID) -> Command | None: ...

    async def save_grounded_answer(self, answer: GroundedAnswer) -> None: ...

    async def save_translation(self, translation: Translation) -> None: ...

    async def save_audio_response(self, audio: AudioResponse) -> None: ...

    async def get_translation_for_answer(self, answer_id: UUID) -> Translation | None: ...

    async def get_audio_for_translation(self, translation_id: UUID) -> AudioResponse | None: ...

    async def get_audio_response(self, audio_id: UUID) -> AudioResponse | None: ...

    async def append_event(self, command_id: UUID, event: DomainEvent) -> None: ...

    async def list_events(self, command_id: UUID) -> list[DomainEvent]: ...

    async def list_events_with_ids(
        self, command_id: UUID, since_event_id: UUID | None = None
    ) -> list[dict]: ...

    async def list_recent_commands(self, limit: int = 10) -> list[Command]: ...

    async def save_submission(self, submission) -> None: ...

    async def get_submission(self, submission_id: UUID): ...

    async def list_submissions(self, status: str | None = None) -> list: ...

    async def delete_submission(self, submission_id: UUID) -> None: ...
