from typing import Protocol
from uuid import UUID

from domain.conversation.entities import Command, Conversation, GroundedAnswer
from domain.events import DomainEvent
from domain.voice.entities import AudioResponse, Translation


class ConversationRepositoryPort(Protocol):
    async def save_conversation(self, conversation: Conversation) -> None: ...

    async def get_conversation(self, conversation_id: UUID) -> Conversation | None: ...

    async def save_command(self, command: Command) -> None: ...

    async def get_command(self, command_id: UUID) -> Command | None: ...

    async def save_grounded_answer(self, answer: GroundedAnswer) -> None: ...

    async def save_translation(self, translation: Translation) -> None: ...

    async def save_audio_response(self, audio: AudioResponse) -> None: ...

    async def append_event(self, command_id: UUID, event: DomainEvent) -> None: ...

    async def list_events(self, command_id: UUID) -> list[DomainEvent]: ...
